################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.c \
../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.c 

SREC += \
assssss.srec 

C_DEPS += \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.d \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.d 

OBJS += \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.o \
./src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.o 

MAP += \
assssss.map 


# Each subdirectory must supply rules for building sources it contributes
src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/%.o: ../src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/%.c
	$(file > $@.in,-mcpu=cortex-m33 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -O2 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-strict-aliasing -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal -g -D_RENESAS_RA_ -D_RA_CORE=CM33 -D_RA_ORDINAL=1 -I"C:/workspace2/assssss/ra_gen" -I"." -I"C:/workspace2/assssss/ra_cfg/fsp_cfg/bsp" -I"C:/workspace2/assssss/ra_cfg/fsp_cfg" -I"C:/workspace2/assssss/src" -I"C:/workspace2/assssss/ra/fsp/inc" -I"C:/workspace2/assssss/ra/fsp/inc/api" -I"C:/workspace2/assssss/ra/fsp/inc/instances" -I"C:/workspace2/assssss/ra/arm/CMSIS_6/CMSIS/Core/Include" -std=c99 -Wno-stringop-overflow -Wno-format-truncation --param=min-pagesize=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" -x c "$<")
	@echo Building file: $< && arm-none-eabi-gcc @"$@.in"

