/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_980641_12.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_980641_3[] = { "value" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_980641_11_axes[] = { 0 };
const uint32_t ei_dsp_config_980641_11_axes_size = 1;
ei_dsp_config_raw_t ei_dsp_config_980641_11 = {
    11, // uint32_t blockId
    1, // int implementationVersion
    1, // int length of axes
    1.0f // float scale-axes
};

const uint8_t ei_dsp_blocks_980641_3_size = 1;
ei_model_dsp_t ei_dsp_blocks_980641_3[ei_dsp_blocks_980641_3_size] = {
    { // DSP block 11
        11,
        12, // output size
        &extract_raw_features, // DSP function pointer
        (void*)&ei_dsp_config_980641_11, // pointer to config struct
        ei_dsp_config_980641_11_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_980641_11_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        nullptr, // data normalization config
    }
};
const ei_config_tflite_graph_t ei_config_graph_980641_12 = {
    .implementation_version = 1,
    .model = tflite_learn_980641_12,
    .model_size = tflite_learn_980641_12_len,
    .arena_size = tflite_learn_980641_12_arena_size
};

const uint8_t ei_output_tensors_indices_980641_12[1] = { 0 };
const uint8_t ei_output_tensors_size_980641_12 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_980641_12 = {
    .implementation_version = 1,
    .block_id = 12,
    .output_tensors_indices = ei_output_tensors_indices_980641_12,
    .output_tensors_size = ei_output_tensors_size_980641_12,
    .quantized = 0,
    .compiled = 0,
    .graph_config = (void*)&ei_config_graph_980641_12,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_980641_3_size = 1;
const uint32_t ei_learning_block_980641_12_inputs[1] = { 11 };
const uint8_t ei_learning_block_980641_12_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_980641_3[ei_learning_blocks_980641_3_size] = {
    {
        12,
        &run_nn_inference,
        (void*)&ei_learning_block_config_980641_12,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_980641_12_inputs,
        ei_learning_block_980641_12_inputs_size,
    },
};

const size_t ei_postprocessing_blocks_980641_3_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_980641_3[ei_postprocessing_blocks_980641_3_size] = {
    {
        .block_id = 12,
        .type = EI_CLASSIFIER_MODE_REGRESSION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_f32,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 12
    },
};

const uint8_t freeform_outputs_980641_3_size = 0;

uint32_t *freeform_outputs_980641_3 = nullptr;

const ei_impulse_t impulse_980641_3 = {
    .project_id = 980641,
    .project_owner = "thinh972243",
    .project_name = "thinh972243-project-1",
    .impulse_id = 3,
    .impulse_name = "Impulse #3",
    .deploy_version = 3,

    .nn_input_frame_size = 12,
    .raw_sample_count = 12,
    .raw_samples_per_frame = 1,
    .dsp_input_frame_size = 12 * 1,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1,
    .frequency = 0,

    .dsp_blocks_size = ei_dsp_blocks_980641_3_size,
    .dsp_blocks = ei_dsp_blocks_980641_3,

    .learning_blocks_size = ei_learning_blocks_980641_3_size,
    .learning_blocks = ei_learning_blocks_980641_3,

    .postprocessing_blocks_size = ei_postprocessing_blocks_980641_3_size,
    .postprocessing_blocks = ei_postprocessing_blocks_980641_3,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_UNKNOWN,
    .fusion_string = "axis0",
    .slice_size = (12/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 1,
    .categories = ei_classifier_inferencing_categories_980641_3,
    .results_type = EI_CLASSIFIER_TYPE_REGRESSION,
    .freeform_outputs_size = freeform_outputs_980641_3_size,
    .freeform_outputs = freeform_outputs_980641_3
};

ei_impulse_handle_t impulse_handle_980641_3 = ei_impulse_handle_t( &impulse_980641_3 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_980641_3;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_980641_3;
const auto ei_dsp_blocks_size = ei_dsp_blocks_980641_3_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_980641_3;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
