################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/add.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/div.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/if.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/real.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/round.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/select.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/split.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/while.cc \
../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.cc 

SREC += \
CK-RA6M5.srec 

CC_DEPS += \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/add.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/div.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/if.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/real.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/round.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/select.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/split.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/while.d \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.d 

OBJS += \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/add.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/div.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/if.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/real.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/round.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/select.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/split.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/while.o \
./src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.o 

MAP += \
CK-RA6M5.map 


# Each subdirectory must supply rules for building sources it contributes
src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/%.o: ../src/ML_model/edge-impulse-sdk/tensorflow/lite/micro/kernels/%.cc
	$(file > $@.in,-mcpu=cortex-m33 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -O2 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-strict-aliasing -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal -g -D_RA_CORE=CM33 -D_RA_ORDINAL=1 -I"C:/Users/admin/Downloads/CK-RA6M5/ra_gen" -I"C:/Users/admin/Downloads/CK-RA6M5/src/Include" -I"C:/Users/admin/Downloads/CK-RA6M5/src/ML_model" -I"C:/workspace2/assssss/src" -I"." -I"C:/Users/admin/Downloads/CK-RA6M5/ra_cfg/fsp_cfg/bsp" -I"C:/Users/admin/Downloads/CK-RA6M5/ra_cfg/fsp_cfg" -I"C:/Users/admin/Downloads/CK-RA6M5/src" -I"C:/Users/admin/Downloads/CK-RA6M5/ra/fsp/inc" -I"C:/Users/admin/Downloads/CK-RA6M5/ra/fsp/inc/api" -I"C:/Users/admin/Downloads/CK-RA6M5/ra/fsp/inc/instances" -I"C:/Users/admin/Downloads/CK-RA6M5/ra/arm/CMSIS_6/CMSIS/Core/Include" -std=c++11 -fabi-version=0 -Wno-stringop-overflow -Wno-format-truncation --param=min-pagesize=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" -x c++ "$<")
	@echo Building file: $< && arm-none-eabi-g++ @"$@.in"

